### ISSUE TITLE
Document type is not set when creating one file in a folder

### ISSUE THREAD

**Issue by vpasquier** [nuxeo-sandbox/polymer-sample-ui#11]
When submitting a document and creating it within a folder, the type is not set in the request payload and fails to generate this document.

Maybe [here](https://github.com/nuxeo-sandbox/polymer-sample-ui/blob/master/polymer-nuxeo/src/main/app/src/add-file.html#L136) we could have by default ("hardcoded") the document type `File`.

We could test it again [here](https://github.com/nuxeo-sandbox/polymer-sample-ui/blob/master/polymer-nuxeo-mp/ftest/nightwatch/tests/smoke_test.js#L28-L36) to be sure to have created this document.

**Comment by espa77** [comment]
Document creation has been fixed by adding the type `File` to the delType component property by default. Tests to verify document creation also added.
